name: Deploy Site

on:
  push:
    branches: ["master"]

permissions:
  # IMPORTANT: this enables automatic authentication to the server
  id-token: write
  contents: read

jobs:
  deploy-site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "24.x"
          cache: "pnpm"
      - uses: internet-golf/deploy@v0.1.9
      - run: |
          corepack enable
          pnpm i
          pnpm build
          golf create-deployment catullus.stuffedanimal.family --auth github-oidc
          golf deploy-content catullus.stuffedanimal.family --auth github-oidc --files ./dist
